In [2]:
# numpy中的array函数，将list转换成numpy中的数组
import numpy as np
data1 = [1,2,3,4,5,6]
array1 = np.array(data1)
array1

array([1, 2, 3, 4, 5, 6])

In [3]:
data2 = [[1,2,3],[4,5,6]]
array2 = np.array(data2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# dtype查询其类型
array2.dtype

dtype('int32')

In [6]:
# astype改变数据类型
array2_str = array2.astype('str')
array2_str.dtype

dtype('<U11')

In [7]:
# 数组的运算很方便，不需要大量的循环
array1+1

array([2, 3, 4, 5, 6, 7])

In [8]:
array1*array1

array([ 1,  4,  9, 16, 25, 36])

In [9]:
array1*2

array([ 2,  4,  6,  8, 10, 12])

In [10]:
# 数组索引和列表相同，也可直接赋值
array1[2]

3

In [11]:
array1[:2]

array([1, 2])

In [14]:
array1[0]=0
array1

array([0, 2, 3, 4, 5, 6])

In [15]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
array2[0]

array([1, 2, 3])

In [17]:
array2[1][1]

5